[package]
name = "tev_client"
version = "0.1.0"
authors = ["Karel <karel.peeters.leuven@gmail.com>"]
edition = "2018"

description = "An IPC TCP client for tev"
repository="https://github.com/KarelPeeters/tev_client"

license="MIT OR Apache-2.0"

keywords=["exf", "hdr", "tev"]